const products = {
    data :[
        {
        id:1,
        productName : 'adidas black',
        category : 'Topwear',
        price : 45,
        description : 'Stylish and comfortable Adidas blue topwear, perfect for casual outings and sports activities. Features breathable fabric and the iconic Adidas logo',
        image : './images/adidas-black.png',
    },
    {
        id:2,    
        productName : 'beige jacket',
        category : 'Jacket',
        price : 30,
        description : 'A versatile beige jacket that complements any outfit. Made with durable material, it s ideal for cooler weather and adds a touch of sophistication to your look',
        image : './images/beige-jacket.png',
    },
    {
        id:3 ,
        productName : 'blue shoes',
        category : 'Topwear',
        price : 25,
        description : 'Trendy blue shoes that combine style and comfort. With a sleek design and cushioned soles, they re perfect for everyday wear or casual events',
        image : './images/blue-shoes.png',
    },
    {
        id:4 ,
        productName : 'blue t shirt',
        category : 'Topwear',
        price : 10,
        description : 'A classic blue t-shirt, an essential for any wardrobe. Made from soft, breathable cotton, it offers both comfort and a timeless look',
        image : './images/blue-t-shirt.png',
    },
    {
        id:5 ,
        productName : 'brown shoes',
        category : 'Topwear',
        price : 99,
        description : 'Elegant brown shoes crafted for style and durability. With a premium leather finish, they are suitable for both formal occasions and smart-casual settings',
        image : './images/brown-shoes.png',
    },
    {
        id:6 ,
        productName : 'classic watch',
        category : 'Watch',
        price : 50,
        description : 'A timeless classic watch that exudes sophistication. Features a clean dial, reliable quartz movement, and a comfortable strap, making it a perfect accessory for any outfit',
        image : './images/classic-watc.png',
    },
    {
        id:7,
        productName : 'balck jacket',
        category : 'Jacket',
        price : 40,
        description : 'A stylish green jacket that stands out from the crowd. Made with weather-resistant material, it s both practical and fashionable for outdoor adventures',
        image : './images/black-jacket.png',
    },
    {
        id:8,
        productName : 't shirt black',
        category : 'Topwear',
        price : 15,
        description : 'A versatile black t-shirt, a must-have basic for any wardrobe. Its soft fabric and comfortable fit make it perfect for layering or wearing on its own',
        image : './images/t-shirt_black.png',
    },
    {
        id:9,
        productName : 'white bottom',
        category : 'Bottomwear',
        price : 30,
        description : 'Crisp white bottomwear that pairs well with any top. Made from a comfortable, stretchy material, these pants are ideal for both casual and semi-formal occasions',
        image : './images/white-bottom.png',
    },
    {
        id:10,
        productName : 'smart watch',
        category : 'Watch',
        price : 25,
        description : 'A modern smart watch with a sleek white design. Packed with features like fitness tracking, notifications, and heart rate monitoring, it s your perfect digital companion',
        image : './images/white-watch.png',
    },
    {
        id:11,
        productName : 'black watch',
        category : 'Watch',
        price : 60,
        description : 'An elegant black watch that combines style with functionality. Its minimalist design and reliable movement make it suitable for both everyday wear and special occasions',
        image : './images/black-watch.png',
    },
    {
        id:12,
        productName : 'bottom cargo',
        category : 'Bottomwear',
        price : 25,
        description : 'Rugged and practical cargo pants, perfect for outdoor activities or casual wear. With multiple pockets and durable fabric, they offer both style and utility',
        image : './images/bottom-cargo.png',
    },
]
}